- name : dnf update
  dnf:
    name: '*'
    state: latest
    update_cache: yes

- name : dnf install dnf-plugins-core
  package:
    name: dnf-plugins-core
    state: present
- name : dnf config-manager - add docker repo
  command: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo
- name : dnf config-manager - enable docker repo
  command: dnf config-manager --set-enabled docker-ce-stable
  args:
    creates: /etc/yum.repos.d/docker-ce.repo

- name : dnf clean all
  command: dnf clean all

- name : kubectl install docker
  command: dnf makecache
  args:
    creates: /var/cache/dnf

- name : kubectl install docker
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
- name : start docker
  service:  
    name: docker
    state: started
    enabled: true  

- name : add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
- name : verify docker installation
  command: docker --version         
  register: docker_version
- name : print docker version
  debug:
    msg: "{{ docker_version.stdout }}"      
# -   --- IGNORE ---    




